version: "3.8"

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5433:5432"
    volumes:
      - database:/var/lib/postgresql/data
